redis:
    host: localhost
    port: 6379
persistence:
    mode: snapshot
    file: zones/{id}.json
    frequency: 60
    compressed: true
world:
  components: theworldfoundry.components
  modes: theworldfoundry.modes
zones:
    default:
        description: The default zone.
        tick: 2.5
