redis:
    host: localhost
    port: 6379
persistence:
    mode: snapshot
    file: zones/{id}.json
    frequency: 60
    compressed: true
zones:
    default:
        description: The default zone.
        tick: 2.5
